### ISSUE TITLE
im sure it's not pure issue but help

### ISSUE THREAD

**Issue by sandikodev** [dhruvwarrier/intel8080-emulator#1]
iam so poor about computer science
have to try compiling it with gcc 
but i get i8080.h: No such file or directory this error message
thanks for reply

**Comment by mayawarrier** [comment]
No worries! I should have put more detailed build instructions. Run these in an empty folder:

**Install dependencies, get LFS files**
sudo apt update && apt upgrade && apt install git && apt install git-lfs
git clone https://github.com/dhruvwarrier/intel8080-emulator
cd intel8080emulator && git lfs install && git lfs pull 
**For the libi8080emu and libi8080 libraries:**
gcc -c -Wall -std=c89 -lpthread -I libi8080emu/include -I libi8080emu/libi8080/include libi8080emu/src/\*.c libi8080emu/libi8080/src/\*.c
**To build the command line frontend:**
g++ -c -Wall -std=c++11 -lpthread -I libi8080emu/include -I libi8080emu/libi8080/include main.cpp run_tests.cpp
**Link everything together**
mkdir build && mv \*.o build
cp -avr libi8080emu/tests tests/
cd build
g++ -lpthread -o i8080emu \*.o
rm \*.o

This should create an executable i8080emu in the build/ folder, which you can run:
./i8080emu --run-all-tests, for example.
Let me know if this works. I'll add a CMakeList later on so you can automatically generate makefiles.

**Comment by mayawarrier** [comment]
@mh4nx7net I made some mistakes with my original build commands, sorry! This should work, I just tested this on Debian 9.

**Comment by mayawarrier** [comment]
@mh4nx7net I've uploaded a CMakeList and build directions to the README. This should automatically install all dependencies, configure and run the build.
